### ISSUE TITLE
Add Animation/Debug For Learning The Hashes

### ISSUE THREAD

**Issue by cheznewa** [maandree/sha3sum#35]
Hi It's Possible To Add A Animation Or Debug For Learn/Understand The Algorithm Hash?
Like ::::: https://github.com/in3rsha/sha256-animation

**Comment by maandree** [comment]
It is out of scope for both sha3sum and libkeccak, and it's not something I want to do. Hypothetically, if this was to be added to sha3sum, it would first have to be added to libkeccak, but adding it to libkeccak would entail rewriting it almost entirely to support step-level progress hooks which would be too costly (either because the functions would need to check if there are any callbacks or because all code has to be duplicated), and all of it for a single application that is not generally useful. Therefore this is best done by simply forking libkeccak and rewriting it to keccak-animation.
